"""
Copyright (c) 2025, Alibaba Cloud and its affiliates;
Licensed under the CC BY-NC-SA 4.0 License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   https://creativecommons.org/licenses/by-nc-sa/4.0/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import re


def extract_answer_from_text(text: str) -> str | None:
    answer_pattern = r'<choice>\n(.*?)\n</choice>'
    match = re.search(answer_pattern, text, re.DOTALL)

    if not match:
        return None

    answer_str = match.group(1).strip()
    if answer_str in ['1', '2']:
        return answer_str
    else:
        return None

def compute_score_pairwise(data_source, solution_str, ground_truth, extra_info):
    """The scoring function for RL-training pairwise ToolRM.

    Args:
        solution_str: the solution text generated by the trained model
        ground_truth: the ground truth name of superior assistant
    """
    answer = extract_answer_from_text(text=solution_str.strip())
    if answer is None:
        rm_reward = 0
        answer = ""
    else:
        if answer == ground_truth:
            rm_reward = 1
        else:
            rm_reward = 0

    merged = {
        "score": rm_reward,
        "pred_answer": answer,
        "gt_answer": ground_truth
    } | extra_info
    
    return merged
